version: '3.1'

services:

  taskapp:
    image: hesh3am/taskapp:latest
    restart: unless-stopped
    ports:
      - 3033:80
  
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=example # MySQL root password
      - MYSQL_DATABASE=redmine #  REDMINE database name
      - MYSQL_USER=rm_user #  REDMINE database user
      - MYSQL_PASSWORD=1234 #  database password
    volumes:
      - ./mysql/data:/var/lib/mysql
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=1234
  